
version: 2
sources:
    - name: staging
    database: production
    schema: staging

    #loaded_at_field: _metadata__timestamp

    tables:
      - name: fhv_tripdata_2021_01
      - name: green_tripdata_2021_01
      - name: yellow_tripdata_2021_01
      - name: fhvhv_tripdata_2021_01
        #freshness:
          #error_after: {count: 24, period: hour}

models:
    - name: stg_fhbhv_tripdata
      description: staging model with all netflix titles from source
      columns:
          - name: show_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: title
            description: Title of the Netflix show
            tests:
                - not_null

    - name: stg_fhv_tripdata
      description: staging model with all records of movies watched via streaming opting for Netflix
      columns:
          - name: stream_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: stg_green_tripdata
      description: staging model with all netflix titles from source
      columns:
          - name: show_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: title
            description: Title of the Netflix show
            tests:
                - not_null

    - name: stg_yellow_tripdata
      description: staging model with all records of movies watched via streaming opting for Netflix
      columns:
          - name: stream_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null



